/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;


import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.mail.Session;
import javax.mail.Transport;
import javax.swing.JOptionPane;

/**
 *
 * @author prabhanjan
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    
    
    public ContactUs() {
        initComponents();
    }
    
    private void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContactUs = new javax.swing.JPanel();
        lblMessageTitle = new javax.swing.JLabel();
        txttopicName = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblMailId = new javax.swing.JLabel();
        txtMailId = new javax.swing.JTextField();
        lblMailIdPassword = new javax.swing.JLabel();
        txtMailPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contact Us");
        setResizable(false);

        PnlContactUs.setBackground(new java.awt.Color(52, 73, 94));
        PnlContactUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Us", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        lblMessageTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblMessageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMessageTitle.setText("Topic Name");

        lblMessage.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("Message");

        txtMsg.setColumns(20);
        txtMsg.setLineWrap(true);
        txtMsg.setRows(5);
        jScrollPane1.setViewportView(txtMsg);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblMailId.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblMailId.setForeground(new java.awt.Color(255, 255, 255));
        lblMailId.setText("Mail Id");

        lblMailIdPassword.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblMailIdPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblMailIdPassword.setText("Mail Password");

        javax.swing.GroupLayout PnlContactUsLayout = new javax.swing.GroupLayout(PnlContactUs);
        PnlContactUs.setLayout(PnlContactUsLayout);
        PnlContactUsLayout.setHorizontalGroup(
            PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactUsLayout.createSequentialGroup()
                .addGroup(PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContactUsLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlContactUsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMailId, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addGroup(PnlContactUsLayout.createSequentialGroup()
                                .addGroup(PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMailId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMessageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttopicName)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                                    .addComponent(lblMailIdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        PnlContactUsLayout.setVerticalGroup(
            PnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactUsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMailId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMailId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMailIdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMailPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblMessageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContactUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        if(txttopicName.getText().isEmpty()) {
            showMessage("Please Enter Topic Name");
            return;
        } else if(txtMailId.getText().isEmpty()) {
            showMessage("Please Enter Maild");
            return;
        }else if(txtMsg.getText().isEmpty()) {
            showMessage("Please Enter Your Message");
            return;
        } else {
            try {
              // change accordingly
        final String username = txtMailId.getText();  
         
        // change accordingly
        final String password = txtMailPassword.getText();
         
                System.out.println(username + " " + password);
        // or IP address
        final String host = "localhost";
 
        // Get system properties
        Properties props = new Properties();            
         
        // enable authentication
        props.put("mail.smtp.auth", "true");              
         
        // enable STARTTLS
        props.put("mail.smtp.starttls.enable", "true");   
         
        // Setup mail server
        props.put("mail.smtp.host", "smtp.gmail.com");    
         
        // TLS Port
        props.put("mail.smtp.port", "587");               
 
        // creating Session instance referenced to
        // Authenticator object to pass in
        // Session.getInstance argument
        Session session = Session.getInstance(props,
          new javax.mail.Authenticator() {
            
            //override the getPasswordAuthentication method
            protected PasswordAuthentication
                           getPasswordAuthentication() {
                                        
                return new PasswordAuthentication(username,
                                                 password);
            }
          });
  
     MimeMessage message = new MimeMessage(session);  
         message.setFrom(new InternetAddress("prabhanjandhobale31@gmail.com"));  
         message.addRecipient(Message.RecipientType.TO,new InternetAddress(username));  
         message.setSubject(txttopicName.getText());  
         message.setText(txtMsg.getText());  
  
         // Send message  
         Transport.send(message);  
                
                JOptionPane.showMessageDialog(this, "Mail Send Successfully");
            }catch(Exception ex) {
                System.out.println(ex);
                showMessage("Mail not send.");
                return;
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlContactUs;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMailId;
    private javax.swing.JLabel lblMailIdPassword;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessageTitle;
    private javax.swing.JTextField txtMailId;
    private javax.swing.JPasswordField txtMailPassword;
    private javax.swing.JTextArea txtMsg;
    private javax.swing.JTextField txttopicName;
    // End of variables declaration//GEN-END:variables
}
