/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.controller.CreateTopicController;

/**
 *
 * @author prabhanjan
 */
public class CreateTopic extends javax.swing.JFrame {

    /**
     * Creates new form CreateTopic
     */
    public CreateTopic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlCreateTopic = new javax.swing.JPanel();
        lblTopicName = new javax.swing.JLabel();
        txtTopicName = new javax.swing.JTextField();
        lblTopicDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTopicDescription = new javax.swing.JTextArea();
        lblGuide = new javax.swing.JLabel();
        txtGuideName = new javax.swing.JTextField();
        lblAssessibility = new javax.swing.JLabel();
        cmbAccessibility = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Topic");
        setBackground(new java.awt.Color(52, 73, 94));

        PnlCreateTopic.setBackground(new java.awt.Color(52, 73, 94));
        PnlCreateTopic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Topic", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(255, 255, 204))); // NOI18N
        PnlCreateTopic.setToolTipText("");

        lblTopicName.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicName.setForeground(new java.awt.Color(255, 255, 204));
        lblTopicName.setText("Topic Name");

        lblTopicDescription.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicDescription.setForeground(new java.awt.Color(255, 255, 204));
        lblTopicDescription.setText("Topic Description");

        txtTopicDescription.setColumns(20);
        txtTopicDescription.setLineWrap(true);
        txtTopicDescription.setRows(5);
        jScrollPane1.setViewportView(txtTopicDescription);

        lblGuide.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblGuide.setForeground(new java.awt.Color(255, 255, 204));
        lblGuide.setText("Guide Name");

        lblAssessibility.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblAssessibility.setForeground(new java.awt.Color(255, 255, 204));
        lblAssessibility.setText("Accessibility");

        cmbAccessibility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Public", "Private" }));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlCreateTopicLayout = new javax.swing.GroupLayout(PnlCreateTopic);
        PnlCreateTopic.setLayout(PnlCreateTopicLayout);
        PnlCreateTopicLayout.setHorizontalGroup(
            PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCreateTopicLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopicName)
                    .addComponent(lblTopicDescription)
                    .addComponent(lblGuide)
                    .addComponent(lblAssessibility))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtGuideName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTopicName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAccessibility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(PnlCreateTopicLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        PnlCreateTopicLayout.setVerticalGroup(
            PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCreateTopicLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopicName))
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlCreateTopicLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTopicDescription))
                    .addGroup(PnlCreateTopicLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuideName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuide))
                .addGap(57, 57, 57)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessibility)
                    .addComponent(cmbAccessibility, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(PnlCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlCreateTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlCreateTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    void showMessage(JPanel root, String msg) {
        JOptionPane.showMessageDialog(root, msg);
       
    }
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if(txtTopicName.getText().isEmpty()) {
            showMessage(PnlCreateTopic, "Please Enter Topic Name");
        } else if(txtTopicDescription.getText().isBlank()) {
            showMessage(PnlCreateTopic, "Please Enter Topic Discription");
        } else if(txtGuideName.getText().isEmpty()) {
            showMessage(PnlCreateTopic, "Please Enter Guide Name");
        } else if(cmbAccessibility.getSelectedItem().toString().equals("Select")) {
            showMessage(PnlCreateTopic, "Please Select Accessibility");
        } else {
            try {
                    ArrayList<String> topic = new ArrayList<String>();
                    topic.add(txtTopicName.getText());
                    topic.add(txtTopicDescription.getText());
                    topic.add(txtGuideName.getText());
                    topic.add(cmbAccessibility.getSelectedItem().toString());
                    
                    int chk = new CreateTopicController().createTopic(topic);
                    
                    if(chk == 1) {
                        showMessage(PnlCreateTopic, "Topic Created Successfully !");
                        txtTopicName.setText("");
                        txtTopicDescription.setText("");
                        txtGuideName.setText("");
                        cmbAccessibility.setSelectedIndex(0);
                    } else {
                        showMessage(PnlCreateTopic, "Error : Topic Not Created !");
                    }
                  
            } catch(Exception ex) {
                showMessage(PnlCreateTopic, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTopic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlCreateTopic;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbAccessibility;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessibility;
    private javax.swing.JLabel lblGuide;
    private javax.swing.JLabel lblTopicDescription;
    private javax.swing.JLabel lblTopicName;
    private javax.swing.JTextField txtGuideName;
    private javax.swing.JTextArea txtTopicDescription;
    private javax.swing.JTextField txtTopicName;
    // End of variables declaration//GEN-END:variables
}
