/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.CreateTopicController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author prabhanjan
 */
public class EditTopic extends javax.swing.JFrame {

    /**
     * Creates new form EditTopic
     */
    
     ArrayList<String> topics;
    
    public void addinCmbTopic() {
         try {
            topics = new CreateTopicController().getTopic();
            System.out.println(topics.size());
            if(topics.size() <=0){
                JOptionPane.showMessageDialog(PnlEditTopic, "No Data Found");
                return;
            } else {
                cmbTopicName.addItem("Select");
                for (String topic : topics) {
                    cmbTopicName.addItem(topic);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(PnlEditTopic, ex.getMessage());
        }
    }
    
    public EditTopic() {
        initComponents();
        addinCmbTopic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlEditTopic = new javax.swing.JPanel();
        lblTopicName = new javax.swing.JLabel();
        lblTopicDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTopicDescription = new javax.swing.JTextArea();
        lblGuide = new javax.swing.JLabel();
        txtGuideName = new javax.swing.JTextField();
        lblAssessibility = new javax.swing.JLabel();
        cmbAccessibility = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cmbTopicName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Topic");

        PnlEditTopic.setBackground(new java.awt.Color(52, 73, 94));
        PnlEditTopic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Topic", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        PnlEditTopic.setToolTipText("");

        lblTopicName.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicName.setForeground(new java.awt.Color(255, 255, 204));
        lblTopicName.setText("Topic Name");

        lblTopicDescription.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicDescription.setForeground(new java.awt.Color(255, 255, 204));
        lblTopicDescription.setText("Topic Description");

        txtTopicDescription.setColumns(20);
        txtTopicDescription.setLineWrap(true);
        txtTopicDescription.setRows(5);
        jScrollPane1.setViewportView(txtTopicDescription);

        lblGuide.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblGuide.setForeground(new java.awt.Color(255, 255, 204));
        lblGuide.setText("Guide Name");

        lblAssessibility.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblAssessibility.setForeground(new java.awt.Color(255, 255, 204));
        lblAssessibility.setText("Accessibility");

        cmbAccessibility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Public", "Private" }));

        btnCreate.setText("Create");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlEditTopicLayout = new javax.swing.GroupLayout(PnlEditTopic);
        PnlEditTopic.setLayout(PnlEditTopicLayout);
        PnlEditTopicLayout.setHorizontalGroup(
            PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEditTopicLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopicName)
                    .addComponent(lblTopicDescription)
                    .addComponent(lblGuide)
                    .addComponent(lblAssessibility))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGuideName)
                        .addComponent(cmbAccessibility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(cmbTopicName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(PnlEditTopicLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        PnlEditTopicLayout.setVerticalGroup(
            PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEditTopicLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTopicName)
                    .addComponent(cmbTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEditTopicLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTopicDescription)
                        .addGap(65, 65, 65))
                    .addGroup(PnlEditTopicLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuide)
                    .addComponent(txtGuideName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssessibility, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbAccessibility, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(PnlEditTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlEditTopic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlEditTopic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTopic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlEditTopic;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbAccessibility;
    private javax.swing.JComboBox<String> cmbTopicName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessibility;
    private javax.swing.JLabel lblGuide;
    private javax.swing.JLabel lblTopicDescription;
    private javax.swing.JLabel lblTopicName;
    private javax.swing.JTextField txtGuideName;
    private javax.swing.JTextArea txtTopicDescription;
    // End of variables declaration//GEN-END:variables
}
