/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.controller.DataOperationsController;
import com.controller.CreateTopicController;
import java.sql.SQLException;


/**
 *
 * @author prabhanjan
 */
public class EditData extends javax.swing.JFrame {

    /**
     * Creates new form EditData
     */
    
    ArrayList<String> topics;
    ArrayList data;
    public EditData() {
        initComponents();
        addinCmbTopic();
        
    }
    
    public EditData(ArrayList data) {
        this();
        if(data.get(0).equals("TextData")) {
            cmbTopicName.setSelectedItem(data.get(2));
            cmbTextTitle.addItem(data.get(3).toString());
            txtAddText.setText(data.get(4).toString());
        }else if(data.get(0).equals("LinkData")) {
            TbpAddData.setSelectedIndex(1);
            cmbTopicNameLink.setSelectedItem(data.get(2));
            cmbLinkTitle.addItem(data.get(3).toString());
            txtLinks.setText(data.get(4).toString());
        }
    }
    
    public void addinCmbTopic() {
         try {
            topics = new CreateTopicController().getTopic();
            System.out.println(topics.size());
            if(topics.size() <=0){
                JOptionPane.showMessageDialog(this, "No Data Found");
                return;
            } else {
                cmbTopicName.addItem("Select");
                cmbTopicNameLink.addItem("Select");
                for (String topic : topics) {
                    cmbTopicName.addItem(topic);
                    cmbTopicNameLink.addItem(topic);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    public void clearLinks() {
        cmbTopicNameLink.setSelectedIndex(0);
        txtLinks.setText("");
        cmbLinkTitle.setSelectedIndex(0);
    }
    
    public void clearScreen() {
        cmbTopicName.setSelectedIndex(0);
        txtAddText.setText("");
        cmbTextTitle.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlAddData = new javax.swing.JPanel();
        TbpAddData = new javax.swing.JTabbedPane();
        PnlAddText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddText = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTextTitle = new javax.swing.JLabel();
        lblTopicNameText = new javax.swing.JLabel();
        cmbTopicName = new javax.swing.JComboBox<>();
        cmbTextTitle = new javax.swing.JComboBox<>();
        btnSearchText = new javax.swing.JButton();
        btnSearchTextData = new javax.swing.JButton();
        PnlAddLinks = new javax.swing.JPanel();
        lblLinkTitle = new javax.swing.JLabel();
        lblLinks = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLinks = new javax.swing.JTextArea();
        btnUpdateLinks = new javax.swing.JButton();
        btnClearLinks = new javax.swing.JButton();
        lblTopicNameLink = new javax.swing.JLabel();
        cmbTopicNameLink = new javax.swing.JComboBox<>();
        cmbLinkTitle = new javax.swing.JComboBox<>();
        btnSearchLinks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Data");
        setResizable(false);

        PnlAddData.setBackground(new java.awt.Color(52, 73, 94));
        PnlAddData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        TbpAddData.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        PnlAddText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 24))); // NOI18N

        txtAddText.setColumns(20);
        txtAddText.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        txtAddText.setLineWrap(true);
        txtAddText.setRows(5);
        jScrollPane1.setViewportView(txtAddText);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblTextTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTextTitle.setText("Title");

        lblTopicNameText.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicNameText.setText("Topic");

        btnSearchText.setText("Search");
        btnSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTextActionPerformed(evt);
            }
        });

        btnSearchTextData.setText("Search");
        btnSearchTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTextDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlAddTextLayout = new javax.swing.GroupLayout(PnlAddText);
        PnlAddText.setLayout(PnlAddTextLayout);
        PnlAddTextLayout.setHorizontalGroup(
            PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddTextLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(PnlAddTextLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(PnlAddTextLayout.createSequentialGroup()
                        .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTopicNameText))
                        .addGap(18, 18, 18)
                        .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTopicName, 0, 585, Short.MAX_VALUE)
                            .addComponent(cmbTextTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchTextData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        PnlAddTextLayout.setVerticalGroup(
            PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddTextLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTopicNameText)
                    .addComponent(cmbTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextTitle)
                    .addComponent(cmbTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PnlAddTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TbpAddData.addTab("Add Text", PnlAddText);

        PnlAddLinks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Links", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 24))); // NOI18N

        lblLinkTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblLinkTitle.setText("Link Title");

        lblLinks.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblLinks.setText("Links");

        txtLinks.setColumns(20);
        txtLinks.setLineWrap(true);
        txtLinks.setRows(5);
        jScrollPane2.setViewportView(txtLinks);

        btnUpdateLinks.setText("Update");
        btnUpdateLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLinksActionPerformed(evt);
            }
        });

        btnClearLinks.setText("Clear");
        btnClearLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLinksActionPerformed(evt);
            }
        });

        lblTopicNameLink.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTopicNameLink.setText("Topic");

        btnSearchLinks.setText("Search");
        btnSearchLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlAddLinksLayout = new javax.swing.GroupLayout(PnlAddLinks);
        PnlAddLinks.setLayout(PnlAddLinksLayout);
        PnlAddLinksLayout.setHorizontalGroup(
            PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddLinksLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnUpdateLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(btnClearLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(PnlAddLinksLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopicNameLink)
                    .addGroup(PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLinks)
                        .addComponent(lblLinkTitle)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                        .addComponent(cmbLinkTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAddLinksLayout.createSequentialGroup()
                            .addComponent(cmbTopicNameLink, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlAddLinksLayout.setVerticalGroup(
            PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddLinksLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTopicNameLink)
                .addGap(18, 18, 18)
                .addGroup(PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTopicNameLink, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLinkTitle)
                .addGap(18, 18, 18)
                .addComponent(cmbLinkTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblLinks)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PnlAddLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        TbpAddData.addTab("Add Links", PnlAddLinks);

        javax.swing.GroupLayout PnlAddDataLayout = new javax.swing.GroupLayout(PnlAddData);
        PnlAddData.setLayout(PnlAddDataLayout);
        PnlAddDataLayout.setHorizontalGroup(
            PnlAddDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddDataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TbpAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlAddDataLayout.setVerticalGroup(
            PnlAddDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAddDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlAddData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlAddData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLinksActionPerformed
        clearLinks();
    }//GEN-LAST:event_btnClearLinksActionPerformed

    private void btnUpdateLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLinksActionPerformed
        if(cmbTopicNameLink.getSelectedItem().equals("Select")){
            JOptionPane.showMessageDialog(this, "Please Select Topic.");
            return;
        }else if(cmbLinkTitle.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please Select Topic.");
            return;
        }else if(txtLinks.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Links.");
            return;
        }else {
            ArrayList data = new ArrayList();
            ArrayList dt;
            try {
                dt = new CreateTopicController().getTopicData(cmbTopicName.getSelectedItem().toString());
                data.add(dt.get(0));
                data.add(cmbLinkTitle.getSelectedItem());
                data.add(txtLinks.getText());

                System.out.println(data);

                int chk = new DataOperationsController().addDataLinks(data);
                if(chk == 1){
                    JOptionPane.showMessageDialog(this, "Data Inserted Successfully.");
                    clearLinks();
                }
                else
                JOptionPane.showMessageDialog(this, "ERROR: Data not inserted");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateLinksActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearScreen();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(cmbTextTitle.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please Select Title.");
            return;
        } else if(txtAddText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Text Data.");
            return;
        } else {
           
            try {
                int chk = new DataOperationsController().UpdateData(cmbTextTitle.getSelectedItem().toString(), "TextData", txtAddText.getText());
                if(chk == 1){
                    JOptionPane.showMessageDialog(this, "Data Updated Successfully.");
                    clearScreen();
                }
                else
                JOptionPane.showMessageDialog(this, "ERROR: Data not Updated");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTextActionPerformed
        ArrayList dt;
        try {
            dt = new CreateTopicController().getTopicData(cmbTopicName.getSelectedItem().toString());
       
            data = new DataOperationsController().getTopicData("TextData", Integer.parseInt(dt.get(0).toString()));
            cmbTextTitle.addItem("Select");
            for (Object dtt : data) {
                cmbTextTitle.addItem(dtt.toString());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchTextActionPerformed

    private void btnSearchLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLinksActionPerformed
        ArrayList dt;
        try {
            dt = new CreateTopicController().getTopicData(cmbTopicNameLink.getSelectedItem().toString());
            data = new DataOperationsController().getTopicData("TextLinks", Integer.parseInt(dt.get(0).toString()));     
            cmbLinkTitle.addItem("Select");
            for (Object dtt : data) {
                cmbLinkTitle.addItem(dtt.toString());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchLinksActionPerformed

    private void btnSearchTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTextDataActionPerformed
        ArrayList dt;
        try{
            dt = new DataOperationsController().getData(cmbTextTitle.getSelectedItem().toString(), "TextData");
            System.out.println(dt);
            txtAddText.setText(dt.get(3).toString());
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchTextDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlAddData;
    private javax.swing.JPanel PnlAddLinks;
    private javax.swing.JPanel PnlAddText;
    private javax.swing.JTabbedPane TbpAddData;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearLinks;
    private javax.swing.JButton btnSearchLinks;
    private javax.swing.JButton btnSearchText;
    private javax.swing.JButton btnSearchTextData;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateLinks;
    private javax.swing.JComboBox<String> cmbLinkTitle;
    private javax.swing.JComboBox<String> cmbTextTitle;
    private javax.swing.JComboBox<String> cmbTopicName;
    private javax.swing.JComboBox<String> cmbTopicNameLink;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLinkTitle;
    private javax.swing.JLabel lblLinks;
    private javax.swing.JLabel lblTextTitle;
    private javax.swing.JLabel lblTopicNameLink;
    private javax.swing.JLabel lblTopicNameText;
    private javax.swing.JTextArea txtAddText;
    private javax.swing.JTextArea txtLinks;
    // End of variables declaration//GEN-END:variables
}
