/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author prabhanjan
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        String imgPath = "assets/projectImages/research.jpg";

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imgPath));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        Image dimg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),Image.SCALE_SMOOTH);
        
        ImageIcon imgThisImg = new ImageIcon(dimg);
        lblImage.setIcon(imgThisImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlHome = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        MenuMain = new javax.swing.JMenuBar();
        MnCreateTopic = new javax.swing.JMenu();
        MnICreateTopic = new javax.swing.JMenuItem();
        MnIEditTopic = new javax.swing.JMenuItem();
        MnIDeleteTopic = new javax.swing.JMenuItem();
        MnlShowTopic = new javax.swing.JMenuItem();
        MnAddData = new javax.swing.JMenu();
        MnIAddData = new javax.swing.JMenuItem();
        MnlUpdateData = new javax.swing.JMenuItem();
        MnlShowData = new javax.swing.JMenuItem();
        MnSetting = new javax.swing.JMenu();
        MnIEditAccount = new javax.swing.JMenuItem();
        MnIContact = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Research Management System");
        setResizable(false);

        PnlHome.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout PnlHomeLayout = new javax.swing.GroupLayout(PnlHome);
        PnlHome.setLayout(PnlHomeLayout);
        PnlHomeLayout.setHorizontalGroup(
            PnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
        );
        PnlHomeLayout.setVerticalGroup(
            PnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        MnCreateTopic.setText("Topic");

        MnICreateTopic.setText("Create Topic");
        MnICreateTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnICreateTopicActionPerformed(evt);
            }
        });
        MnCreateTopic.add(MnICreateTopic);

        MnIEditTopic.setText("Edit Topic");
        MnIEditTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIEditTopicActionPerformed(evt);
            }
        });
        MnCreateTopic.add(MnIEditTopic);

        MnIDeleteTopic.setText("Delete Topic");
        MnIDeleteTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIDeleteTopicActionPerformed(evt);
            }
        });
        MnCreateTopic.add(MnIDeleteTopic);

        MnlShowTopic.setText("Show Topics");
        MnlShowTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnlShowTopicActionPerformed(evt);
            }
        });
        MnCreateTopic.add(MnlShowTopic);

        MenuMain.add(MnCreateTopic);

        MnAddData.setText("Data");

        MnIAddData.setText("Add Data");
        MnIAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIAddDataActionPerformed(evt);
            }
        });
        MnAddData.add(MnIAddData);

        MnlUpdateData.setText("Update Data");
        MnlUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnlUpdateDataActionPerformed(evt);
            }
        });
        MnAddData.add(MnlUpdateData);

        MnlShowData.setText("Show Data");
        MnlShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnlShowDataActionPerformed(evt);
            }
        });
        MnAddData.add(MnlShowData);

        MenuMain.add(MnAddData);

        MnSetting.setText("Setting");

        MnIEditAccount.setText("Edit Account");
        MnIEditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIEditAccountActionPerformed(evt);
            }
        });
        MnSetting.add(MnIEditAccount);

        MnIContact.setText("Contact Us");
        MnIContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIContactActionPerformed(evt);
            }
        });
        MnSetting.add(MnIContact);

        MenuMain.add(MnSetting);

        setJMenuBar(MenuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnICreateTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnICreateTopicActionPerformed

        new CreateTopic().setVisible(true);
    }//GEN-LAST:event_MnICreateTopicActionPerformed

    private void MnIEditTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIEditTopicActionPerformed
        new EditTopic().setVisible(true);
    }//GEN-LAST:event_MnIEditTopicActionPerformed

    private void MnIDeleteTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIDeleteTopicActionPerformed
        new DeleteTopic().setVisible(true);
    }//GEN-LAST:event_MnIDeleteTopicActionPerformed

    private void MnIAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIAddDataActionPerformed
        new AddData().setVisible(true);
    }//GEN-LAST:event_MnIAddDataActionPerformed

    private void MnlUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnlUpdateDataActionPerformed
        new EditData().setVisible(true);
    }//GEN-LAST:event_MnlUpdateDataActionPerformed

    private void MnIEditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIEditAccountActionPerformed
        try {
            new Account().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnIEditAccountActionPerformed

    private void MnIContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIContactActionPerformed
         new ContactUs().setVisible(true);
    }//GEN-LAST:event_MnIContactActionPerformed

    private void MnlShowTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnlShowTopicActionPerformed
        try {
            new ShowTopicData().setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_MnlShowTopicActionPerformed

    private void MnlShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnlShowDataActionPerformed
        new ShowAllData().setVisible(true);
    }//GEN-LAST:event_MnlShowDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuMain;
    private javax.swing.JMenu MnAddData;
    private javax.swing.JMenu MnCreateTopic;
    private javax.swing.JMenuItem MnIAddData;
    private javax.swing.JMenuItem MnIContact;
    private javax.swing.JMenuItem MnICreateTopic;
    private javax.swing.JMenuItem MnIDeleteTopic;
    private javax.swing.JMenuItem MnIEditAccount;
    private javax.swing.JMenuItem MnIEditTopic;
    private javax.swing.JMenu MnSetting;
    private javax.swing.JMenuItem MnlShowData;
    private javax.swing.JMenuItem MnlShowTopic;
    private javax.swing.JMenuItem MnlUpdateData;
    private javax.swing.JPanel PnlHome;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
